ALB: remove ? from path_pattern (#9039)
* ALB: remove ? from path_pattern

The ALB docs say:

```
? (matches exactly 1 character)
```

so this requires a character at end. At least in `weep`, the URL is a
simple string, so `weep` fails to list roles or get credentials without
this change. The error looks like:

```
Error: failed to unmarshal JSON: invalid character '<' looking for
beginning of value
```

since `/get_roles` or `/get_credentials` gets redirected to the ALB OIDC
login.

Ref:
https://github.com/Netflix/weep/blob/master/creds/consoleme.go#L148
https://github.com/Netflix/weep/blob/master/creds/consoleme.go#L237

* ALB: use * glob for get_roles/get_credentials path

Co-authored-by: Matthew Lesko <matthew.lesko@nih.gov>